# Generated by Django 3.1.6 on 2021-02-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='remaining_flags',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
