# Generated by Django 3.1.6 on 2021-02-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_remaining_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='remaining_free_cells',
            field=models.PositiveIntegerField(default=380),
        ),
    ]
